import './styles.css';
import './hangar.css';
import * as signalR from '@microsoft/signalr';

type Lang='ru'|'en'; type View='hangar'|'arena'|'battle';
type Profile={id:string;provider:string;displayName:string;avatarUrl?:string|null;credits:number;xp:number;rating:number;victories:number;defeats:number;upgrades:Record<string,number>;level?:number};
type Place={id:string;x:number;y:number}; type Loadout={weapons:string[];modules:Place[]};
type Mod={id:string;name:string;type:string;hp:number;maxHp:number;x:number;y:number;fireTurns:number;shortTurns:number;powered:boolean;condition:string};
type Ship={id:string;name:string;modules:Mod[];weaponIds:string[];repairKits:number;integrity:number};
type Weapon={id:string;name:string;damage:number;accuracy:number}; type Log={turn:number;kind:string;text:string};
type Battle={id:string;turn:number;activeSide:'player'|'enemy';status:string;winner?:string|null;playerShip:Ship;enemyShip:Ship;weapons:Weapon[];log:Log[]};
type Viewer={ownSide:'player'|'enemy';battle:Battle};
type Pilot={id:string;displayName:string;avatarUrl?:string|null;rating:number;level:number;shipPower:number;status:string};
type Challenge={id:string;fromPlayerId:string;fromName:string;toPlayerId:string;toName:string;expiresAt:string;status:string};
type Mode={kind:'fire';weaponId:string}|{kind:'repair'};

const $=document.querySelector<HTMLDivElement>('#app')!;
const tr=(ru:string,en:string)=>lang==='ru'?ru:en;
const esc=(s:unknown)=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]!));
const defaults:Loadout={weapons:['laser','missile'],modules:[
{id:'armor-top',x:50,y:15},{id:'sensor',x:50,y:28},{id:'weapon-left',x:25,y:43},{id:'core',x:50,y:48},{id:'weapon-right',x:75,y:43},{id:'armor-left',x:16,y:59},{id:'hull',x:50,y:65},{id:'armor-right',x:84,y:59},{id:'engine-left',x:35,y:82},{id:'engine-right',x:65,y:82}]};
const weapons=[['laser','Лазер','Laser','╱'],['missile','Ракета','Missile','➤'],['scatter','Дробь','Scatter','✦'],['plasma','Плазма','Plasma','●']] as const;
const mods:Record<string,[string,string,string]>= {'armor-top':['Броня','Armor','ARM'],sensor:['Сенсор','Sensor','SNS'],'weapon-left':['Левое орудие','Port weapon','WPN'],core:['Ядро','Core','CORE'],'weapon-right':['Правое орудие','Starboard weapon','WPN'],'armor-left':['Левая броня','Port armor','ARM'],hull:['Корпус','Hull','HULL'],'armor-right':['Правая броня','Starboard armor','ARM'],'engine-left':['Левый двигатель','Port engine','ENG'],'engine-right':['Правый двигатель','Starboard engine','ENG']};
const upgrades=[['core','Ядро','Core'],['engines','Двигатели','Engines'],['weapons','Орудия','Weapons'],['armor','Броня','Armor'],['sensors','Сенсоры','Sensors'],['hull','Корпус','Hull'],['fire-protection','Огнезащита','Fire protection'],['electrical-shielding','Экранирование','Shielding']] as const;

let lang:Lang=localStorage.getItem('cf-language')==='en'?'en':'ru', view:View='hangar', profile:Profile|null=null, loadout:Loadout=structuredClone(defaults), pilots:Pilot[]=[], online=0;
let battle:Battle|null=null, own:'player'|'enemy'='player', pvp=false, mode:Mode={kind:'fire',weaponId:'laser'}, incoming:Challenge|null=null, outgoing:Challenge|null=null, busy=false, toast='', version={version:'0.1.0',commit:'unknown'};
let hub:signalR.HubConnection|null=null, drag:{id:string;field:HTMLElement;el:HTMLElement}|null=null;

async function api<T>(url:string,init?:RequestInit):Promise<T>{const r=await fetch(url,{...init,headers:{'Content-Type':'application/json',...(init?.headers||{})}});if(!r.ok){let m=`HTTP ${r.status}`;try{const b=await r.json() as {error?:string};m=b.error||m}catch{}throw new Error(m)}return r.status===204?undefined as T:r.json()}
const err=(e:unknown)=>e instanceof Error?e.message:tr('Ошибка','Error');
async function identity(){try{profile=await api<Profile>('/api/auth/me')}catch{profile=await api<Profile>('/api/auth/guest',{method:'POST',body:'{}'})}}
async function save(show=true){try{loadout=await api<Loadout>('/api/loadout',{method:'PUT',body:JSON.stringify(loadout)});if(show)toast=tr('Сборка сохранена на сервере','Build saved on server')}catch(e){toast=err(e)}render()}
async function refreshProfile(){profile=await api<Profile>('/api/profile').catch(()=>profile)}
async function upgrade(key:string){if(busy)return;busy=true;render();try{profile=await api<Profile>('/api/profile/upgrades',{method:'POST',body:JSON.stringify({upgrade:key})});toast=tr('Улучшение установлено','Upgrade installed')}catch(e){toast=err(e)}busy=false;render()}

async function connect(){hub=new signalR.HubConnectionBuilder().withUrl('/hubs/game').withAutomaticReconnect([0,1000,3000,5000]).build();
 hub.on('arenaState',(s:{online:number;players:Pilot[]})=>{online=s.online;pilots=s.players;render()});
 hub.on('arenaChanged',(s:{online:number})=>{online=s.online;void arena()});
 hub.on('challengeReceived',(c:Challenge)=>{incoming=c;toast=tr(`${c.fromName} вызывает вас на бой`,`${c.fromName} challenges you`);render()});
 hub.on('challengeSent',(c:Challenge)=>{outgoing=c;render()}); hub.on('challengeDeclined',()=>{outgoing=null;toast=tr('Вызов отклонён','Challenge declined');render()}); hub.on('challengeClosed',()=>{incoming=null;render()});
 hub.on('matchStarted',(v:Viewer)=>enter(v)); hub.on('battleUpdated',(v:Viewer)=>{own=v.ownSide;battle=v.battle;busy=false;render()}); hub.on('profileChanged',()=>void refreshProfile().then(render)); hub.onreconnected(()=>void arena());
 try{await hub.start();await arena()}catch{toast=tr('PvP-соединение временно недоступно','PvP connection unavailable');render()}}
async function arena(){if(hub?.state===signalR.HubConnectionState.Connected){try{const s=await hub.invoke<{online:number;players:Pilot[]}>('GetArena');online=s.online;pilots=s.players}catch{}}render()}
async function challenge(id:string){try{await save(false);await hub?.invoke('Challenge',id)}catch(e){toast=err(e);render()}}
async function answer(ok:boolean){if(!incoming)return;busy=true;render();try{await save(false);await hub?.invoke('RespondChallenge',incoming.id,ok);if(!ok)incoming=null}catch(e){toast=err(e)}busy=false;render()}
function enter(v:Viewer){incoming=outgoing=null;own=v.ownSide;battle=v.battle;pvp=true;view='battle';mode={kind:'fire',weaponId:myShip()?.weaponIds[0]||'laser'};render()}
async function ai(){busy=true;render();try{await save(false);battle=await api<Battle>('/api/battles/ai',{method:'POST',body:'{}'});own='player';pvp=false;view='battle';mode={kind:'fire',weaponId:battle.playerShip.weaponIds[0]||'laser'}}catch(e){toast=err(e)}busy=false;render()}
async function action(id:string,friendly:boolean){if(!battle||busy||battle.status!=='active'||battle.activeSide!==own)return;if(mode.kind==='repair'&&!friendly||mode.kind==='fire'&&friendly)return;busy=true;render();const req={turn:battle.turn,action:mode.kind,weaponId:mode.kind==='fire'?mode.weaponId:null,targetModuleId:id,clientActionId:crypto.randomUUID()};try{if(pvp)await hub?.invoke('Act',req);else{battle=await api<Battle>(`/api/battles/${battle.id}/actions`,{method:'POST',body:JSON.stringify(req)});busy=false;if(battle.status==='finished')await refreshProfile();render()}}catch(e){toast=err(e);busy=false;render()}}
const myShip=()=>!battle?null:own==='player'?battle.playerShip:battle.enemyShip; const enemyShip=()=>!battle?null:own==='player'?battle.enemyShip:battle.playerShip;

function frame(body:string){return `<div class="cf-space"></div><header class="cf-top"><button class="cf-logo" data-view="hangar">✦ <b>COSMIC FIGHT</b></button><nav><button data-view="hangar" class="${view==='hangar'?'on':''}">${tr('АНГАР','HANGAR')}</button><button data-view="arena" class="${view==='arena'?'on':''}">${tr('АРЕНА','ARENA')} <em>${online}</em></button></nav><div class="cf-user"><button data-lang="ru" class="${lang==='ru'?'on':''}">RU</button><button data-lang="en" class="${lang==='en'?'on':''}">EN</button><span>${esc(profile?.displayName||'Pilot')} · ${profile?.rating||1000}</span></div></header><main class="cf-main">${body}</main>${incoming?modal():''}${toast?`<div class="cf-toast">${esc(toast)}</div>`:''}<footer class="cf-footer">Cosmic Fight v${esc(version.version)} · ${esc(version.commit)} <span>ASP.NET Core · PostgreSQL · SignalR</span></footer>`}
function hangar(){const power=100+(profile?Object.values(profile.upgrades).reduce((a,b)=>a+b,0)*18:0);return frame(`<section class="cf-hero"><div><small>${tr('КОНСТРУКТОР КОРАБЛЯ','SHIP CONSTRUCTOR')}</small><h1>${tr('Соберите корабль перед боем','Build your ship before battle')}</h1><p>${tr('Перетаскивайте модули, установите два орудия и усилите системы. Сборка хранится на сервере.','Drag modules, equip two weapons and upgrade systems. The build is stored on the server.')}</p></div><strong>${tr('МОЩЬ','POWER')}<b>${power}</b></strong></section><section class="cf-hangar"><article class="cf-panel"><div class="cf-title"><div><small>${tr('ВАШ КОРАБЛЬ','YOUR SHIP')}</small><h2>CF–Vanguard</h2></div><div><button id="reset">${tr('Сброс','Reset')}</button><button id="save">${tr('Сохранить','Save')}</button></div></div>${shipBuilder()}</article><aside><section class="cf-panel cf-armory"><div class="cf-title"><h2>${tr('Установите 2 орудия','Equip 2 weapons')}</h2><b>${loadout.weapons.length}/2</b></div>${weapons.map(w=>`<button data-equip="${w[0]}" class="${loadout.weapons.includes(w[0])?'on':''}"><i>${w[3]}</i><span><b>${tr(w[1],w[2])}</b><small>${loadout.weapons.includes(w[0])?tr('УСТАНОВЛЕНО','EQUIPPED'):tr('НАЖМИТЕ ДЛЯ ВЫБОРА','CLICK TO SELECT')}</small></span></button>`).join('')}</section>${upgradePanel()}</aside></section><div class="cf-launch"><span><b>${tr('Корабль готов?','Ship ready?')}</b>${tr(' Выходите в живую арену.',' Enter the live arena.')}</span><button id="go-arena">${tr('В ОНЛАЙН-АРЕНУ','ENTER ONLINE ARENA')} →</button></div>`)}
function shipBuilder(){return `<div class="cf-builder"><div class="cf-hull"><i class="nose"></i><i class="body"></i><i class="wing l"></i><i class="wing r"></i><i class="engine l"></i><i class="engine r"></i></div>${loadout.modules.map(p=>`<button data-drag="${p.id}" class="cf-module ${kind(p.id)}" style="left:${p.x}%;top:${p.y}%"><b>${mods[p.id]?.[2]||'MOD'}</b><span>${tr(mods[p.id]?.[0]||p.id,mods[p.id]?.[1]||p.id)}</span></button>`).join('')}<div class="cf-dragtip">↔ ${tr('ПЕРЕТАСКИВАЙТЕ МОДУЛИ','DRAG MODULES')}</div></div>`}
function kind(id:string){return id.includes('armor')?'armor':id.includes('weapon')?'weapon':id.includes('engine')?'engine':id}
function upgradePanel(){return `<section class="cf-panel cf-upgrades"><div class="cf-title"><h2>${tr('Модернизация','Upgrades')}</h2><b>${profile?.credits||0} C</b></div>${upgrades.map(u=>{const lv=profile?.upgrades[u[0]]||0,c=100*(lv+1);return `<button data-upgrade="${u[0]}" ${lv>=5||busy?'disabled':''}><span><b>${tr(u[1],u[2])}</b><small>Lv ${lv}/5</small></span><em>${lv>=5?'MAX':`+ ${c} C`}</em></button>`}).join('')}</section>`}
function arenaView(){return frame(`<section class="cf-hero"><div><small>${tr('ОНЛАЙН-АРЕНА','ONLINE ARENA')}</small><h1>${tr('Выберите живого соперника','Choose a live opponent')}</h1><p>${tr('Вызов приходит мгновенно. После подтверждения сервер создаёт один общий бой для двух устройств.','The challenge arrives instantly. After acceptance the server creates one shared battle for both devices.')}</p></div><strong class="live">● <b>${online}</b>${tr('ОНЛАЙН','ONLINE')}</strong></section><section class="cf-arena"><article class="cf-panel"><div class="cf-title"><h2>${tr('Пилоты в сети','Pilots online')}</h2><button id="refresh">↻</button></div><div class="cf-pilots">${pilots.length?pilots.map(pilot).join(''):`<div class="cf-empty">${tr('Откройте игру на другом устройстве под другим аккаунтом или гостевой сессией.','Open the game on another device with another account or guest session.')}</div>`}</div></article><aside class="cf-panel cf-help"><h2>${tr('Как начинается PvP','How PvP starts')}</h2><ol><li>1. ${tr('Выберите пилота','Choose a pilot')}</li><li>2. ${tr('Он получит запрос','They receive a request')}</li><li>3. ${tr('Он принимает бой','They accept')}</li><li>4. ${tr('Сервер синхронизирует ходы','Server syncs turns')}</li></ol><button id="ai">${tr('Тестовый бой с AI','Test battle vs AI')}</button>${outgoing?`<div class="cf-wait">${tr('Ждём ответ от','Waiting for')} <b>${esc(outgoing.toName)}</b>…</div>`:''}</aside></section>`)}
function pilot(p:Pilot){const ok=p.status==='online_available';return `<div class="cf-pilot"><span class="cf-avatar">${p.avatarUrl?`<img src="${esc(p.avatarUrl)}">`:esc(p.displayName[0])}<i class="${ok?'ok':'busy'}"></i></span><div><b>${esc(p.displayName)}</b><small>Lv ${p.level} · ${p.rating} ELO · ${tr('мощь','power')} ${p.shipPower}</small></div><em>${ok?tr('ГОТОВ','READY'):tr('В БОЮ','IN BATTLE')}</em><button data-challenge="${p.id}" ${!ok||!!outgoing?'disabled':''}>⚔ ${tr('ВЫЗВАТЬ','CHALLENGE')}</button></div>`}
function battleView(){if(!battle)return hangar();const me=myShip()!,foe=enemyShip()!,turn=battle.status==='active'&&battle.activeSide===own;return frame(`<section class="cf-battle-head"><div><small>${pvp?'PVP · LIVE':tr('ТРЕНИРОВКА · AI','TRAINING · AI')}</small><h1>${esc(me.name)} <em>VS</em> ${esc(foe.name)}</h1></div><strong class="${turn?'mine':''}">${tr('ХОД','TURN')} ${battle.turn}<b>${battle.status==='finished'?tr('БОЙ ЗАВЕРШЁН','BATTLE OVER'):turn?tr('ВАШ ХОД','YOUR TURN'):tr('ХОД СОПЕРНИКА','OPPONENT TURN')}</b></strong></section><section class="cf-panel cf-battle"><div class="cf-battlefield">${combatShip(foe,false)}<div class="cf-vs">VS</div>${combatShip(me,true)}</div><div class="cf-weapons">${battle.weapons.filter(w=>me.weaponIds.includes(w.id)).map(w=>`<button data-weapon="${w.id}" class="${mode.kind==='fire'&&mode.weaponId===w.id?'on':''}" ${!turn||busy?'disabled':''}><i>${weapons.find(x=>x[0]===w.id)?.[3]||'•'}</i><b>${weaponName(w.id)}</b><small>${w.damage} DMG · ${Math.round(w.accuracy*100)}%</small></button>`).join('')}<button id="repair" class="${mode.kind==='repair'?'on':''}" ${!turn||busy?'disabled':''}>✚ <b>${tr('Ремонт','Repair')}</b><small>${me.repairKits} kits</small></button></div><p class="cf-command">${mode.kind==='repair'?tr('Выберите повреждённый модуль своего корабля','Select a damaged friendly module'):tr('Выберите модуль противника. Урон рассчитывает сервер.','Select an enemy module. Damage is calculated by the server.')}</p></section><section class="cf-battle-bottom"><article class="cf-panel"><h2>${tr('Журнал боя','Battle log')}</h2>${battle.log.slice(-8).reverse().map(x=>`<p><b>T${x.turn}</b> ${esc(x.text)}</p>`).join('')}</article><aside class="cf-panel"><h2>${tr('Серверный контроль','Server authority')}</h2><p>${tr('Клиент отправляет только оружие и цель. Сервер решает попадание, урон, броню, пожар, КЗ, ход и победу.','The client sends only weapon and target. Server decides hit, damage, armor, fire, shorts, turn and victory.')}</p>${battle.status==='finished'?`<button id="back">${tr('ВЕРНУТЬСЯ В АРЕНУ','BACK TO ARENA')}</button>`:''}</aside></section>`)}
function combatShip(s:Ship,friendly:boolean){return `<div class="cf-combatship ${friendly?'friend':'enemy'}"><div class="cf-shipname"><b>${esc(s.name)}</b><strong>${s.integrity}%</strong></div><div class="cf-integrity"><i style="width:${s.integrity}%"></i></div><div class="cf-combatfield"><div class="cf-hull"><i class="nose"></i><i class="body"></i><i class="wing l"></i><i class="wing r"></i><i class="engine l"></i><i class="engine r"></i></div>${s.modules.map(m=>`<button data-module="${m.id}" data-friendly="${friendly}" class="cf-hit ${kind(m.id)} ${String(m.condition).toLowerCase()}" style="left:${m.x}%;top:${m.y}%" ${m.hp<=0?'disabled':''}><b>${mods[m.id]?.[2]||'MOD'}</b><i><span style="width:${Math.max(0,m.hp/m.maxHp*100)}%"></span></i>${m.fireTurns?'🔥':''}${m.shortTurns?'⚡':''}</button>`).join('')}</div></div>`}
const weaponName=(id:string)=>{const w=weapons.find(x=>x[0]===id);return w?tr(w[1],w[2]):id};
function modal(){return `<div class="cf-modal"><div><small>${tr('ВХОДЯЩИЙ ВЫЗОВ','INCOMING CHALLENGE')}</small><strong>⚔</strong><h2>${esc(incoming?.fromName)}</h2><p>${tr('вызывает вас на дуэль','challenges you to a duel')}</p><button id="decline">${tr('Отклонить','Decline')}</button><button id="accept">${tr('ПРИНЯТЬ БОЙ','ACCEPT DUEL')}</button></div></div>`}
function render(){document.documentElement.lang=lang;$.innerHTML=view==='hangar'?hangar():view==='arena'?arenaView():battleView();bind()}
function bind(){document.querySelectorAll<HTMLButtonElement>('[data-view]').forEach(b=>b.onclick=()=>{view=b.dataset.view as View;if(view==='arena')void arena();else render()});document.querySelectorAll<HTMLButtonElement>('[data-lang]').forEach(b=>b.onclick=()=>{lang=b.dataset.lang as Lang;localStorage.setItem('cf-language',lang);render()});
 document.querySelector('#save')?.addEventListener('click',()=>void save());document.querySelector('#reset')?.addEventListener('click',()=>{loadout=structuredClone(defaults);render()});document.querySelector('#go-arena')?.addEventListener('click',()=>void save(false).then(()=>{view='arena';void arena()}));
 document.querySelectorAll<HTMLButtonElement>('[data-equip]').forEach(b=>b.onclick=()=>{const id=b.dataset.equip!;if(loadout.weapons.includes(id)){if(loadout.weapons.length>1)loadout.weapons=loadout.weapons.filter(x=>x!==id)}else loadout.weapons=loadout.weapons.length>=2?[loadout.weapons[1],id]:[...loadout.weapons,id];render()});document.querySelectorAll<HTMLButtonElement>('[data-upgrade]').forEach(b=>b.onclick=()=>void upgrade(b.dataset.upgrade!));
 document.querySelectorAll<HTMLElement>('[data-drag]').forEach(el=>el.onpointerdown=e=>{const field=el.closest('.cf-builder') as HTMLElement;drag={id:el.dataset.drag!,field,el};el.setPointerCapture?.(e.pointerId)});document.querySelector('#refresh')?.addEventListener('click',()=>void arena());document.querySelector('#ai')?.addEventListener('click',()=>void ai());document.querySelectorAll<HTMLButtonElement>('[data-challenge]').forEach(b=>b.onclick=()=>void challenge(b.dataset.challenge!));
 document.querySelector('#accept')?.addEventListener('click',()=>void answer(true));document.querySelector('#decline')?.addEventListener('click',()=>void answer(false));document.querySelectorAll<HTMLButtonElement>('[data-weapon]').forEach(b=>b.onclick=()=>{mode={kind:'fire',weaponId:b.dataset.weapon!};render()});document.querySelector('#repair')?.addEventListener('click',()=>{mode={kind:'repair'};render()});document.querySelectorAll<HTMLButtonElement>('[data-module]').forEach(b=>b.onclick=()=>void action(b.dataset.module!,b.dataset.friendly==='true'));document.querySelector('#back')?.addEventListener('click',()=>{battle=null;pvp=false;view='arena';void arena()})}
window.addEventListener('pointermove',e=>{if(!drag)return;const r=drag.field.getBoundingClientRect(),x=Math.max(6,Math.min(94,(e.clientX-r.left)/r.width*100)),y=Math.max(8,Math.min(92,(e.clientY-r.top)/r.height*100));const p=loadout.modules.find(x=>x.id===drag!.id);if(p){p.x=+x.toFixed(1);p.y=+y.toFixed(1)}drag.el.style.left=`${x}%`;drag.el.style.top=`${y}%`});window.addEventListener('pointerup',()=>{if(drag){drag=null;toast=tr('Позиция изменена — сохраните сборку','Position changed — save the build');render()}});
async function boot(){render();const q=new URLSearchParams(location.search);try{version=await fetch('/version.json',{cache:'no-store'}).then(r=>r.json()).catch(()=>version);await identity();loadout=await api<Loadout>('/api/loadout').catch(()=>structuredClone(defaults));if(q.get('auth')==='success')toast=tr('Google подключён: профиль синхронизируется между устройствами','Google connected: profile syncs across devices');if(q.has('auth'))history.replaceState({},'',location.pathname);await connect();render()}catch(e){toast=err(e);render()}}
if('serviceWorker'in navigator)window.addEventListener('load',()=>navigator.serviceWorker.register('/sw.js').catch(()=>{}));void boot();
